# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2

updates:
  - package-ecosystem: 'github-actions'
    open-pull-requests-limit: 1
    multi-ecosystem-groups: updates
    patterns: ['*']
    directory: '/'
    groups:
      security:
        patterns: ['*']
        applies-to: security-updates

  - package-ecosystem: 'bun'
    open-pull-requests-limit: 1
    multi-ecosystem-groups: updates
    directory: '/'
    groups:
      security:
        patterns: ['*']
        applies-to: security-updates

  - package-ecosystem: 'gomod'
    open-pull-requests-limit: 1
    multi-ecosystem-groups: updates
    directories: ['**/*']
    patterns: ['*']
    groups:
      security:
        applies-to: security-updates
        patterns: ['*']

  - package-ecosystem: 'helm'
    open-pull-requests-limit: 1
    multi-ecosystem-groups: updates
    directories: ['**/*']
    patterns: ['*']
    groups:
      security:
        applies-to: security-updates
        patterns: ['*']

multi-ecosystem-groups:
  updates:
    schedule:
      day: 'sunday'
      interval: 'weekly'
    commit-message:
      prefix: 'deps'
