# .goreleaser.yml
# Build customization
builds:
  - binary: configurd
    main:   ./cmd/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X cmd/actions/version.version={{.Version}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

# .goreleaser.yml
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

brews:
  # Reporitory to push the tap to.
  - github:
      owner: foomo
      name: homebrew-configurd
    caveats: "configurd -h"
    homepage: "https://github.com/foomo/configurd"
    description: "CLI utility manage infrastructure as code with helm"
